- name: Reiniciar NGINX
  containers.podman.podman_container:
  name: nginx_frontend
  image: docker.io/library/nginx:latest
  state: started
  restart_policy: always
  publish:
    - "8081:80"
  volume:
    - "{{ frontend_deploy_dest }}:{{ frontend_deploy_dest }}:Z"
    - "/var/www/nginx/config/nginx.conf:/etc/nginx/nginx.conf:Z"
  working_dir: "{{ frontend_deploy_dest }}"
  force_restart: true